# Generated by Django 6.0.5 on 2026-05-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
